### ISSUE TITLE
Internal and UMI reads 

### ISSUE THREAD

**Issue by cfusterot** [vincenthahaut/FLASH-Seq#3]
Dear Vicent, 

I am starting to analyze a FLASH-seq experiment and I have a _probably very silly_ question concerning the concept of **Internal** and **UMI** reads. In order to properly analyze a single-cell experiment, how should these two count matrices be combined? I am not entirely understanding how should I treat those genes that appear in both **UMI** and **Internal** matrices and whether the latter could be used to properly account for duplication events on the internal read counts. 

Thanks a lot for your time!

**Comment by vincenthahaut** [comment]
Hi!

For the purpose of the paper I always treated them separately. Using the UMI for "accurate" counting and the internal reads for "relative" counting and isoform identification. Typically internal reads contain more information than UMI ones for various reasons related to the methodology

The idea behind UMI vs Internal is coming from the first Smart-seq3 paper. I advice you to read it :-)

https://pubmed.ncbi.nlm.nih.gov/32518404/

If you want to merge both information, their work include an isoform reconstruction and quantification pipeline using similar data. It is possible to use FLASH-seq data with it but it can be a bit tricky. 
However, I recently read this paper nature.com/articles/s41587-023-01815-7 which states that 43% of the isoforms reconstructed by their pipeline are wrong. I do not know if this because their pipeline is problematic or because of the high rate of strand-invasion events I detected in their data (corrected in FLASH-seq and partially in Smart-seq3-express). 

In my opinion, the benefits of full-length methods is mainly in the greater gene-body coverage rather than in the quantification accuracy. UMI are problematic in these methods because they complicate the wet-lab part and they harbor a high error-rate introduced by RT/PCR/Sequencing.
These days, I typically do not use UMI and focus on the internal reads using standard differential expression tools except if accurate isoform quantification is absolutely required. 

Hope this helps. 

If not, do not hesitate to send me an email (vincent.hahaut [a]iob.ch) to organise a meeting :-) 

Vincent

**Comment by cfusterot** [comment]
This is soo useful! Thank you so much for the quick response :-)
